import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Footer/Footer'
const roboto = Roboto({ 
  subsets: ['latin'],
  weight: ["100"  , "300" , "400" , "500" ,  "700" , "900"] })

export const metadata: Metadata = {
  title: 'Local host',
  description: 'Generated by create next app',
}
import Nav from '@/assets/Nav/Nav'
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
